import type { CaptchaPoint, CaptchaTrackPoint } from './protocol';
export const COORDINATE_MAX = 10_000;
export const DEFAULT_TRACK_LIMIT = 128;
export function clampCoordinate(value: number) { return Math.max(0, Math.min(COORDINATE_MAX, Math.round(value))); }
export function normalizePoint(clientX: number, clientY: number, rect: Pick<DOMRect, 'left' | 'top' | 'width' | 'height'>): CaptchaPoint { return { x: clampCoordinate(rect.width ? ((clientX - rect.left) / rect.width) * COORDINATE_MAX : 0), y: clampCoordinate(rect.height ? ((clientY - rect.top) / rect.height) * COORDINATE_MAX : 0) }; }
export function trackPoint(point: CaptchaPoint, t: number, type?: string): CaptchaTrackPoint { return { ...point, t: Math.max(0, Math.round(t)), ...(type ? { type } : {}) }; }
export function appendTrack(track: CaptchaTrackPoint[], point: CaptchaTrackPoint, limit = DEFAULT_TRACK_LIMIT) { if (limit <= 0) return []; if (track.length < limit) return [...track, point]; const sampled = track.filter((_, index) => index === 0 || index % Math.ceil(track.length / Math.max(1, limit - 2)) === 0).slice(0, limit - 1); return [...sampled, point].slice(-limit); }
const CURVES: Record<number, CaptchaPoint[]> = { 1:[{x:900,y:6500},{x:2200,y:4300},{x:3700,y:5000},{x:5200,y:3000},{x:6900,y:4200},{x:9000,y:2600}], 2:[{x:900,y:7000},{x:1800,y:3900},{x:3100,y:5200},{x:4300,y:2600},{x:5700,y:5600},{x:7000,y:3300},{x:9000,y:5000}], 3:[{x:800,y:6200},{x:1900,y:3000},{x:3300,y:6100},{x:4700,y:2400},{x:6100,y:5700},{x:7600,y:2900},{x:9200,y:4300}] };
export function curvePoint(version: number, progress: number): CaptchaPoint { const curve=CURVES[version] ?? CURVES[3]; const scaled=Math.max(0,Math.min(1,progress))*(curve.length-1); const i=Math.min(curve.length-2,Math.floor(scaled)); const f=scaled-i; return {x:clampCoordinate(curve[i].x+(curve[i+1].x-curve[i].x)*f),y:clampCoordinate(curve[i].y+(curve[i+1].y-curve[i].y)*f)}; }
export function leadingZeroBits(bytes: Uint8Array) { let bits = 0; for (const byte of bytes) { if (byte === 0) { bits += 8; continue; } for (let mask = 0x80; (byte & mask) === 0; mask >>= 1) bits += 1; break; } return bits; }
export async function solvePow(salt: string, difficulty: number, signal?: AbortSignal, batchSize = 64): Promise<string> { const encoder = new TextEncoder(); for (let nonce = 0; nonce < Number.MAX_SAFE_INTEGER; nonce += 1) { if (signal?.aborted) throw new DOMException('Cancelled', 'AbortError'); const proof = nonce.toString(36); const hash = new Uint8Array(await crypto.subtle.digest('SHA-256', encoder.encode(`${salt}:${proof}`))); if (leadingZeroBits(hash) >= difficulty) return proof; if (nonce % batchSize === batchSize - 1) await new Promise<void>((resolve) => setTimeout(resolve, 0)); } throw new Error('Proof of work exhausted'); }
