import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { AngleChallenge } from './AngleChallenge';

afterEach(cleanup);
describe('AngleChallenge',()=>{
  it('renders one independent circular image and rotates it with the slider',()=>{render(<AngleChallenge challenge={{image:'/square.jpg',initialAngle:270}} onComplete={vi.fn()}/>);const root=screen.getByTestId('angle-challenge');expect(root.querySelectorAll('img')).toHaveLength(1);expect(root.querySelector('[class*=roundStage]')).not.toBeNull();fireEvent.change(screen.getByRole('slider'),{target:{value:'2500'}});expect(screen.getByTestId('angle-image').parentElement?.style.getPropertyValue('--captcha-angle')).toBe('0deg')});
  it('binds the normalized angle to the final slider track coordinate',()=>{const onComplete=vi.fn();render(<AngleChallenge challenge={{image:'/square.jpg',initialAngle:315}} onComplete={onComplete}/>);const slider=screen.getByRole('slider');fireEvent.pointerDown(slider,{pointerId:2});fireEvent.change(slider,{target:{value:'2500'}});fireEvent.pointerUp(slider,{pointerId:2});expect(onComplete).toHaveBeenCalledWith(expect.objectContaining({angle:45,track:[expect.objectContaining({x:0,type:'down'}),expect.objectContaining({x:2500,type:'move'}),expect.objectContaining({x:2500,type:'up'})]}))});
  it('serializes slider 1234 as a normalized integer angle',()=>{const onComplete=vi.fn();render(<AngleChallenge challenge={{image:'/square.jpg',initialAngle:359}} onComplete={onComplete}/>);const slider=screen.getByRole('slider');fireEvent.pointerDown(slider,{pointerId:5});fireEvent.change(slider,{target:{value:'1234'}});fireEvent.pointerUp(slider,{pointerId:5});expect(onComplete).toHaveBeenCalledWith(expect.objectContaining({angle:43,track:expect.arrayContaining([expect.objectContaining({x:1234,type:'up'})])}))});
  it('submits a one-step keyboard adjustment without requiring a large drag',()=>{const onComplete=vi.fn();render(<AngleChallenge challenge={{image:'/square.jpg',initialAngle:359}} onComplete={onComplete}/>);const slider=screen.getByRole('slider');fireEvent.change(slider,{target:{value:'27'}});fireEvent.keyDown(slider,{key:'ArrowRight'});fireEvent.change(slider,{target:{value:'28'}});fireEvent.keyUp(slider,{key:'ArrowRight'});expect(onComplete).toHaveBeenCalledWith(expect.objectContaining({angle:0,track:[expect.objectContaining({x:27,type:'down'}),expect.objectContaining({x:28,type:'up'})]}))});
  it('honors the issued minimum duration for a fast pointer completion',()=>{const onComplete=vi.fn();render(<AngleChallenge challenge={{image:'/square.jpg',minDurationMs:375}} onComplete={onComplete}/>);const slider=screen.getByRole('slider');fireEvent.pointerDown(slider,{pointerId:7});fireEvent.change(slider,{target:{value:'25'}});fireEvent.pointerUp(slider,{pointerId:7});expect(onComplete).toHaveBeenCalledWith(expect.objectContaining({durationMs:375,track:expect.arrayContaining([expect.objectContaining({type:'up',t:375})])}))});
  it('honors the issued minimum duration for a fast keyboard completion',()=>{const onComplete=vi.fn();render(<AngleChallenge challenge={{image:'/square.jpg',minDurationMs:440}} onComplete={onComplete}/>);const slider=screen.getByRole('slider');fireEvent.keyDown(slider,{key:'ArrowRight'});fireEvent.change(slider,{target:{value:'1'}});fireEvent.keyUp(slider,{key:'ArrowRight'});expect(onComplete).toHaveBeenCalledWith(expect.objectContaining({durationMs:440,track:expect.arrayContaining([expect.objectContaining({type:'up',t:440})])}))});
});
