import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { RotatePuzzleChallenge } from './RotatePuzzleChallenge';

afterEach(cleanup);
describe('RotatePuzzleChallenge',()=>{
  it('keeps the background fixed and rotates only the center piece',()=>{render(<RotatePuzzleChallenge challenge={{image:'/scene.jpg',initialAngle:90}} onComplete={vi.fn()}/>);const root=screen.getByTestId('rotate-puzzle-challenge');expect(root.querySelectorAll('img')).toHaveLength(1);expect(root.querySelector('img')?.style.transform).toBe('');expect(screen.getByTestId('rotate-piece').parentElement?.style.getPropertyValue('--captcha-angle')).toBe('90deg')});
  it('binds the submitted angle to the final slider track coordinate',()=>{const onComplete=vi.fn();render(<RotatePuzzleChallenge challenge={{image:'/scene.jpg',initialAngle:90}} onComplete={onComplete}/>);const slider=screen.getByRole('slider');fireEvent.pointerDown(slider,{pointerId:1});fireEvent.change(slider,{target:{value:'2500'}});fireEvent.pointerUp(slider,{pointerId:1});expect(onComplete).toHaveBeenCalledWith(expect.objectContaining({angle:180,track:[expect.objectContaining({x:0,type:'down'}),expect.objectContaining({x:2500,type:'move'}),expect.objectContaining({x:2500,type:'up'})]}))});
  it('serializes a non-integral raw angle as a normalized integer',()=>{const onComplete=vi.fn();render(<RotatePuzzleChallenge challenge={{image:'/scene.jpg',initialAngle:0}} onComplete={onComplete}/>);const slider=screen.getByRole('slider');fireEvent.pointerDown(slider,{pointerId:4});fireEvent.change(slider,{target:{value:'1234'}});fireEvent.pointerUp(slider,{pointerId:4});expect(onComplete).toHaveBeenCalledWith(expect.objectContaining({angle:44,track:expect.arrayContaining([expect.objectContaining({x:1234,type:'up'})])}))});
  it('submits a one-step keyboard adjustment with matching track coordinates',()=>{const onComplete=vi.fn();render(<RotatePuzzleChallenge challenge={{image:'/scene.jpg',initialAngle:0}} onComplete={onComplete}/>);const slider=screen.getByRole('slider');fireEvent.change(slider,{target:{value:'1234'}});fireEvent.keyDown(slider,{key:'ArrowRight'});fireEvent.change(slider,{target:{value:'1235'}});fireEvent.keyUp(slider,{key:'ArrowRight'});expect(onComplete).toHaveBeenCalledWith(expect.objectContaining({angle:44,track:[expect.objectContaining({x:1234,type:'down'}),expect.objectContaining({x:1235,type:'up'})]}))});
  it('does not submit a release without an interaction start',()=>{const onComplete=vi.fn();render(<RotatePuzzleChallenge challenge={{image:'/scene.jpg'}} onComplete={onComplete}/>);fireEvent.pointerUp(screen.getByRole('slider'),{pointerId:1});expect(onComplete).not.toHaveBeenCalled()});
  it('does not submit a cancelled drag',()=>{const onComplete=vi.fn();render(<RotatePuzzleChallenge challenge={{image:'/scene.jpg'}} onComplete={onComplete}/>);const slider=screen.getByRole('slider');fireEvent.pointerDown(slider,{pointerId:3});fireEvent.pointerCancel(slider,{pointerId:3});expect(onComplete).not.toHaveBeenCalled()});
  it('honors the issued minimum duration for a fast pointer completion',()=>{const onComplete=vi.fn();render(<RotatePuzzleChallenge challenge={{image:'/scene.jpg',minDurationMs:360}} onComplete={onComplete}/>);const slider=screen.getByRole('slider');fireEvent.pointerDown(slider,{pointerId:6});fireEvent.change(slider,{target:{value:'25'}});fireEvent.pointerUp(slider,{pointerId:6});expect(onComplete).toHaveBeenCalledWith(expect.objectContaining({durationMs:360,track:expect.arrayContaining([expect.objectContaining({type:'up',t:360})])}))});
  it('honors the issued minimum duration for a fast keyboard completion',()=>{const onComplete=vi.fn();render(<RotatePuzzleChallenge challenge={{image:'/scene.jpg',minDurationMs:420}} onComplete={onComplete}/>);const slider=screen.getByRole('slider');fireEvent.keyDown(slider,{key:'ArrowRight'});fireEvent.change(slider,{target:{value:'1'}});fireEvent.keyUp(slider,{key:'ArrowRight'});expect(onComplete).toHaveBeenCalledWith(expect.objectContaining({durationMs:420,track:expect.arrayContaining([expect.objectContaining({type:'up',t:420})])}))});
});
