package activation

import (
	"context"
	"crypto/x509"
	"errors"
	"fmt"
	"reflect"
	"time"

	"github.com/LaokeQwQ/CheeseWAF/internal/crp"
)

var (
	// ErrProductionContract is the stable fail-closed sentinel for a missing
	// or inconsistent CRP production dependency graph.
	ErrProductionContract = errors.New("CRP production contract is not satisfied")
	// ErrProductionDurability is returned when a test/local in-memory adapter
	// is offered for a state which must survive process restart.
	ErrProductionDurability = errors.New("CRP production dependency is not durable")
	// ErrProductionAuditUnavailable means an activation decision could not be
	// durably recorded. A grant is never returned without its audit record.
	ErrProductionAuditUnavailable = errors.New("CRP production authorization audit is unavailable")
)

// DurableAuthorizationState marks an authorization state implementation that
// has a restart-safe, cross-process backing store. MemoryAuthorizationState
// intentionally does not implement this interface.
type DurableAuthorizationState interface {
	AuthorizationState
	Durable() bool
}

// DurableAuthorizationProvider marks the control-plane authority that owns
// permission, fence, confirmation and replay decisions in durable storage.
// A provider's in-process cache is not sufficient for this contract.
type DurableAuthorizationProvider interface {
	AuthorizationProvider
	Durable() bool
}

// LiveFenceAuthorizationProvider is the production proof that authorization
// decisions are bound to a live consensus fence, not merely persisted in a
// durable authorization database.
type LiveFenceAuthorizationProvider interface {
	DurableAuthorizationProvider
	LiveFenceBound() bool
}

// AuthorizationAuditEvent contains only metadata. Fence tokens, confirmation
// actors, request/response payloads and CRP bytes must never be copied into an
// activation audit stream.
type AuthorizationAuditEvent struct {
	EventID          string            `json:"event_id"`
	Operation        string            `json:"operation"`
	Outcome          string            `json:"outcome"`
	At               time.Time         `json:"at"`
	Identity         TransportIdentity `json:"identity"`
	RequestID        string            `json:"request_id"`
	AuthorizationID  string            `json:"authorization_id,omitempty"`
	Action           crp.RuntimeAction `json:"action"`
	Permission       Permission        `json:"permission"`
	PluginKey        string            `json:"plugin_key"`
	ManifestIdentity string            `json:"manifest_identity"`
	ExpectedRevision uint64            `json:"expected_revision"`
}

// DurableAuthorizationAudit is the append-only metadata audit boundary used
// by the production control-plane provider. Append must be idempotent for an
// EventID so transport retries cannot create ambiguous audit history.
type DurableAuthorizationAudit interface {
	Append(context.Context, AuthorizationAuditEvent) error
	Durable() bool
}

// IdempotentAuthorizationAudit is the explicit production capability proof
// that an audit sink handles retries safely. Idempotent must only return true
// when appending the same EventID with the same metadata is a no-op, while a
// conflicting payload for an existing EventID is rejected. Durable storage by
// itself does not prove this property, so production composition requires this
// capability in addition to DurableAuthorizationAudit.
type IdempotentAuthorizationAudit interface {
	DurableAuthorizationAudit
	Idempotent() bool
}

// ProductionContractOptions is the complete CRP activation dependency graph.
// There is intentionally no constructor that fills any field with an
// in-memory default.
type ProductionContractOptions struct {
	ClusterID    string
	ClientCA     *x509.CertPool
	State        AuthorizationState
	Provider     AuthorizationProvider
	Audit        DurableAuthorizationAudit
	ControlPlane ControlPlaneClient
	Sidecars     SidecarManager
	Clock        func() time.Time
}

// ProductionControlPlaneHandlerOptions is the narrow production admission
// contract for the CRP authorization HTTP handler. It deliberately excludes
// outbound transports and sidecar launchers so a control-plane process can
// mount the durable authorization authority without inventing client-side
// dependencies or a local sidecar substitute.
type ProductionControlPlaneHandlerOptions struct {
	ClusterID string
	ClientCA  *x509.CertPool
	State     AuthorizationState
	Provider  AuthorizationProvider
	Audit     DurableAuthorizationAudit
	Clock     func() time.Time
}

// NewProductionControlPlaneHandler constructs a production authorization
// handler only after durable state, a durable provider and an explicitly
// EventID-idempotent durable audit have all been proven. There are no memory
// fallbacks and no authority is generated by this constructor.
func NewProductionControlPlaneHandler(opts ProductionControlPlaneHandlerOptions) (*ControlPlaneHandler, error) {
	if !validTransportField(opts.ClusterID, 128) || opts.ClientCA == nil {
		return nil, fmt.Errorf("%w: cluster ID and client CA are required", ErrProductionContract)
	}
	state, ok := opts.State.(DurableAuthorizationState)
	if !ok || isNilActivationDependency(state) || !state.Durable() {
		return nil, fmt.Errorf("%w: authorization state", ErrProductionDurability)
	}
	provider, ok := opts.Provider.(DurableAuthorizationProvider)
	if !ok || isNilActivationDependency(provider) || !provider.Durable() {
		return nil, fmt.Errorf("%w: authorization provider", ErrProductionDurability)
	}
	fencedProvider, ok := opts.Provider.(LiveFenceAuthorizationProvider)
	if !ok || isNilActivationDependency(fencedProvider) || !fencedProvider.LiveFenceBound() {
		return nil, fmt.Errorf("%w: live consensus fence provider is required", ErrProductionContract)
	}
	audit, ok := productionAuthorizationAudit(opts.Audit)
	if !ok {
		return nil, fmt.Errorf("%w: durable EventID-idempotent authorization audit is required", ErrProductionAuditUnavailable)
	}
	if opts.Clock == nil {
		opts.Clock = time.Now
	}
	handler, err := NewControlPlaneHandler(ControlPlaneHandlerOptions{
		ClusterID: opts.ClusterID,
		Role:      "waf",
		ClientCA:  opts.ClientCA,
		Clock:     opts.Clock,
		State:     state,
		Provider:  auditedAuthorizationProvider{delegate: provider, audit: audit, clock: opts.Clock},
	})
	if err != nil {
		return nil, err
	}
	if err := ValidateProductionControlPlaneHandler(handler); err != nil {
		return nil, err
	}
	return handler, nil
}

// ProductionContract is a validated, immutable composition-root seam. It
// does not open listeners or mutate RuntimeStore; the launcher owns those
// lifecycle operations after it has supplied this contract.
type ProductionContract struct {
	clusterID string
	clientCA  *x509.CertPool
	state     AuthorizationState
	provider  AuthorizationProvider
	control   ControlPlaneClient
	sidecars  SidecarManager
	clock     func() time.Time
}

// NewProductionContract validates every dependency before a production CRP
// handler or activation service can be constructed. In particular, memory
// state, non-durable providers/audits and mismatched node identities are
// rejected instead of being silently accepted as a local substitute.
func NewProductionContract(opts ProductionContractOptions) (*ProductionContract, error) {
	handler, err := NewProductionControlPlaneHandler(ProductionControlPlaneHandlerOptions{
		ClusterID: opts.ClusterID,
		ClientCA:  opts.ClientCA,
		State:     opts.State,
		Provider:  opts.Provider,
		Audit:     opts.Audit,
		Clock:     opts.Clock,
	})
	if err != nil {
		return nil, err
	}
	if isNilActivationDependency(opts.ControlPlane) || isNilActivationDependency(opts.Sidecars) {
		return nil, fmt.Errorf("%w: control-plane and sidecar transports are required", ErrProductionContract)
	}
	controlIdentity := opts.ControlPlane.TransportIdentity()
	if err := validateTransportIdentity(controlIdentity); err != nil || controlIdentity.ClusterID != opts.ClusterID {
		return nil, fmt.Errorf("%w: invalid control-plane identity", ErrProductionContract)
	}
	if sidecarIdentity := opts.Sidecars.TransportIdentity(); !sameTransportIdentity(controlIdentity, sidecarIdentity) {
		return nil, fmt.Errorf("%w: control-plane and sidecar identities differ", ErrProductionContract)
	}
	if opts.Clock == nil {
		opts.Clock = time.Now
	}
	return &ProductionContract{
		clusterID: opts.ClusterID,
		clientCA:  opts.ClientCA,
		state:     handler.state,
		provider:  handler.provider,
		control:   opts.ControlPlane,
		sidecars:  opts.Sidecars,
		clock:     opts.Clock,
	}, nil
}

// ValidateProductionControlPlaneHandler checks the same non-negotiable
// dependency boundary used by the production composition root. It is kept as
// a standalone check so runtimes that receive an already-built handler can
// reject memory-backed state or non-durable providers before mounting it.
func ValidateProductionControlPlaneHandler(h *ControlPlaneHandler) error {
	if h == nil || isNilActivationDependency(h.state) || isNilActivationDependency(h.provider) {
		return ErrProductionContract
	}
	state, ok := h.state.(DurableAuthorizationState)
	if !ok || isNilActivationDependency(state) || !state.Durable() {
		return fmt.Errorf("%w: authorization state is not durable", ErrProductionDurability)
	}
	// Check the audit wrapper and its explicit EventID-idempotence capability
	// before evaluating the wrapper's aggregate Durable result. Otherwise a
	// durable provider wrapped around a durable-but-non-idempotent audit would
	// be misclassified as a generic provider durability failure.
	if !validAuditedAuthorizationProvider(h.provider) {
		return fmt.Errorf("%w: authorization audit wrapper or EventID idempotence proof is missing", ErrProductionAuditUnavailable)
	}
	provider, ok := h.provider.(DurableAuthorizationProvider)
	if !ok || isNilActivationDependency(provider) || !provider.Durable() {
		return fmt.Errorf("%w: authorization provider is not durable", ErrProductionDurability)
	}
	fencedProvider, ok := h.provider.(LiveFenceAuthorizationProvider)
	if !ok || isNilActivationDependency(fencedProvider) || !fencedProvider.LiveFenceBound() {
		return fmt.Errorf("%w: live consensus fence provider is required", ErrProductionContract)
	}
	return nil
}

func productionAuthorizationAudit(value DurableAuthorizationAudit) (IdempotentAuthorizationAudit, bool) {
	if isNilActivationDependency(value) {
		return nil, false
	}
	audit, ok := value.(IdempotentAuthorizationAudit)
	if !ok || isNilActivationDependency(audit) || !audit.Durable() || !audit.Idempotent() {
		return nil, false
	}
	return audit, true
}

func validAuditedAuthorizationProvider(value AuthorizationProvider) bool {
	switch audited := value.(type) {
	case auditedAuthorizationProvider:
		_, ok := productionAuthorizationAudit(audited.audit)
		return ok
	case *auditedAuthorizationProvider:
		if audited == nil {
			return false
		}
		_, ok := productionAuthorizationAudit(audited.audit)
		return ok
	default:
		return false
	}
}

// isNilActivationDependency catches both a nil interface and an interface
// containing a typed-nil pointer. The latter is easy for composition roots to
// produce when an optional adapter is returned through an interface; calling
// Durable or TransportIdentity on it can otherwise panic before fail-closed
// validation gets a chance to reject the graph.
func isNilActivationDependency(value any) bool {
	if value == nil {
		return true
	}
	rv := reflect.ValueOf(value)
	switch rv.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return rv.IsNil()
	default:
		return false
	}
}

// NewControlPlaneHandler returns the protected handler using the durable
// state/provider and audit wrapper validated by NewProductionContract.
func (c *ProductionContract) NewControlPlaneHandler() (*ControlPlaneHandler, error) {
	if c == nil || c.state == nil || c.provider == nil || c.clientCA == nil {
		return nil, ErrProductionContract
	}
	return NewControlPlaneHandler(ControlPlaneHandlerOptions{
		ClusterID: c.clusterID,
		Role:      "waf",
		ClientCA:  c.clientCA,
		Clock:     c.clock,
		State:     c.state,
		Provider:  c.provider,
	})
}

// ControlPlane and Sidecars expose only the already-validated transport
// adapters for the activation service constructor.
func (c *ProductionContract) ControlPlane() ControlPlaneClient {
	if c == nil {
		return nil
	}
	return c.control
}

func (c *ProductionContract) Sidecars() SidecarManager {
	if c == nil {
		return nil
	}
	return c.sidecars
}

type auditedAuthorizationProvider struct {
	delegate AuthorizationProvider
	audit    DurableAuthorizationAudit
	clock    func() time.Time
}

var _ AuthorizationStateCoalescingProvider = auditedAuthorizationProvider{}

// Durable preserves the admission property of the wrapped provider. The
// audit decorator must not make an otherwise durable provider look like an
// in-memory test double to the runtime composition root.
func (p auditedAuthorizationProvider) Durable() bool {
	provider, ok := p.delegate.(DurableAuthorizationProvider)
	_, auditOK := productionAuthorizationAudit(p.audit)
	return ok && provider != nil && provider.Durable() && auditOK
}

// LiveFenceBound preserves the live-fence proof through the audit decorator,
// so mount-time validation cannot be bypassed by wrapping an unfenced durable
// provider in a valid audit sink.
func (p auditedAuthorizationProvider) LiveFenceBound() bool {
	provider, ok := p.delegate.(LiveFenceAuthorizationProvider)
	return ok && !isNilActivationDependency(provider) && provider.LiveFenceBound()
}

func (p auditedAuthorizationProvider) Authorize(ctx context.Context, identity TransportIdentity, request AuthorizationRequest) (Authorization, error) {
	authorization, providerErr := p.delegate.Authorize(ctx, identity, request)
	auditErr := p.recordOperation(ctx, "authorize", providerErr == nil, identity, request, authorization)
	if providerErr != nil {
		if auditErr != nil {
			return Authorization{}, errors.Join(providerErr, auditErr)
		}
		return Authorization{}, providerErr
	}
	if auditErr != nil {
		return Authorization{}, auditErr
	}
	return authorization, nil
}

func (p auditedAuthorizationProvider) Validate(ctx context.Context, identity TransportIdentity, authorization Authorization) error {
	providerErr := p.delegate.Validate(ctx, identity, authorization)
	auditErr := p.recordOperation(ctx, "validate", providerErr == nil, identity, authorization.Request, authorization)
	if providerErr != nil {
		if auditErr != nil {
			return errors.Join(providerErr, auditErr)
		}
		return providerErr
	}
	return auditErr
}

func (p auditedAuthorizationProvider) Consume(ctx context.Context, identity TransportIdentity, authorization Authorization) error {
	return p.consumeAndRecord(ctx, identity, authorization, func() error {
		return p.delegate.Consume(ctx, identity, authorization)
	})
}

func (p auditedAuthorizationProvider) UsesAuthorizationState(state AuthorizationState) bool {
	provider, ok := p.delegate.(AuthorizationStateCoalescingProvider)
	return ok && !isNilActivationDependency(provider) && provider.UsesAuthorizationState(state)
}

func (p auditedAuthorizationProvider) ConsumeAfterState(ctx context.Context, identity TransportIdentity, authorization Authorization) error {
	provider, ok := p.delegate.(AuthorizationStateCoalescingProvider)
	if !ok || isNilActivationDependency(provider) {
		return ErrProductionContract
	}
	return p.consumeAndRecord(ctx, identity, authorization, func() error {
		return provider.ConsumeAfterState(ctx, identity, authorization)
	})
}

func (p auditedAuthorizationProvider) consumeAndRecord(ctx context.Context, identity TransportIdentity, authorization Authorization, consume func() error) error {
	providerErr := consume()
	auditErr := p.recordOperation(ctx, "consume", providerErr == nil, identity, authorization.Request, authorization)
	if providerErr != nil {
		if auditErr != nil {
			return errors.Join(providerErr, auditErr)
		}
		return providerErr
	}
	return auditErr
}

func (p auditedAuthorizationProvider) recordOperation(ctx context.Context, operation string, allowed bool, identity TransportIdentity, request AuthorizationRequest, authorization Authorization) error {
	nonce, err := newRequestID()
	if err != nil {
		return fmt.Errorf("%w: generate audit event identity: %v", ErrProductionAuditUnavailable, err)
	}
	return p.record(ctx, authorizationAuditEvent(operation, allowed, p.clock().UTC(), identity, request, authorization, nonce))
}

func (p auditedAuthorizationProvider) record(ctx context.Context, event AuthorizationAuditEvent) error {
	audit, ok := productionAuthorizationAudit(p.audit)
	if !ok {
		return ErrProductionAuditUnavailable
	}
	if err := audit.Append(ctx, event); err != nil {
		return fmt.Errorf("%w: %v", ErrProductionAuditUnavailable, err)
	}
	return nil
}

func authorizationAuditEvent(operation string, allowed bool, at time.Time, identity TransportIdentity, request AuthorizationRequest, authorization Authorization, nonce string) AuthorizationAuditEvent {
	status := "denied"
	if allowed {
		status = "allowed"
	}
	eventID := operation + ":" + request.RequestID
	if authorization.ID != "" {
		eventID += ":" + authorization.ID
	}
	eventID += ":" + nonce
	return AuthorizationAuditEvent{
		EventID: eventID, Operation: operation, Outcome: status, At: at,
		Identity: identity, RequestID: request.RequestID, AuthorizationID: authorization.ID,
		Action: request.Action, Permission: request.Permission, PluginKey: request.Target.Key,
		ManifestIdentity: request.Target.ManifestIdentity, ExpectedRevision: request.ExpectedRevision,
	}
}
